title: glae's random dev thoughts
baseurl: "/blog"
plugins:
  - jemoji
theme: jekyll-theme-cayman
markdown: kramdown
kramdown:
  syntax_highlighter: rouge
  input: GFM
baseurl: "/blog"
url: "https://glae.github.io" 