title: glae's random dev thoughts
plugins:
  - jemoji
  - jekyll-feed
theme: jekyll-theme-cayman 
baseurl: /blog/
url: https://glae.github.io
markdown: kramdown
kramdown:
  syntax_highlighter: rouge
  input: GFM
  auto_ids: true