title: glae's random dev thoughts
plugins:
  - jemoji
  - jekyll-feed
theme: jekyll-theme-cayman 
markdown: CommonMarkGhPages
commonmark:
  options: ["SMART", "FOOTNOTES"]
  extensions: ["strikethrough", "autolink", "table", "tagfilter"]