title: glae's random dev thoughts
plugins:
  - jemoji
  - jekyll-feed
theme: jekyll-theme-cayman 
markdown: kramdown
kramdown:
  syntax_highlighter: rouge
  input: GFM
  auto_ids: true
  auto_id_prefix: true
  auto_id_stripping: true
  toc_levels: 1..3
  